using System;
using System.Collections;
using System.Threading;
using Microsoft.SPOT.Hardware;
using Nrf8001Lib.Commands;
using Nrf8001Lib.Events;
using Nrf8001Lib.Extensions;

namespace Nrf8001Lib
{
    public class Nrf8001
    {
        private OutputPort _req, _rst;
        private InterruptPort _rdy;
        private SPI _spi;
        private Queue _eventQueue;

        /// <summary>
        /// Gets the device state of the nRF8001.
        /// </summary>
        public Nrf8001State State { get; protected set; }
        /// <summary>
        /// Gets the amount of data credits available.
        /// </summary>
        public byte DataCreditAvailable { get; protected set; }

        /// <summary>
        /// Creates a new nRF8001 device interface.
        /// </summary>
        /// <param name="rstPin">The application controller pin that the nRF8001's RST pin is connected to.</param>
        /// <param name="reqPin">The application controller pin that the nRF8001's REQn pin is connected to.</param>
        /// <param name="rdyPin">The application controller pin that the nRF8001's RDYn pin is connected to.</param>
        public Nrf8001(Cpu.Pin rstPin, Cpu.Pin reqPin, Cpu.Pin rdyPin, SPI.SPI_module spiModule)
        {
            _rst = new OutputPort(rstPin, true);
            _req = new OutputPort(reqPin, true);
            
            _rdy = new InterruptPort(rdyPin, false, Port.ResistorMode.Disabled, Port.InterruptMode.InterruptEdgeLow);

            _spi = new SPI(new SPI.Configuration(Cpu.Pin.GPIO_NONE, false, 0, 0, false, true, 100, spiModule));

            State = Nrf8001State.Unknown;
            _eventQueue = new Queue();

            Reset();

            _rdy.OnInterrupt += new NativeEventHandler(OnRdyInterrupt);
        }

        /// <summary>
        /// Resets the nRF8001 by toggling its RST pin.
        /// </summary>
        public void Reset()
        {
            State = Nrf8001State.Resetting;

            _rst.Write(false);
            Thread.Sleep(10);

            _rst.Write(true);
        }

        /// <summary>
        /// Handles the first event in the nRF8001's event queue. Call this method as often as possible from the application controller.
        /// </summary>
        /// <returns>The first event in the event queue.</returns>
        public Nrf8001Event HandleEvent()
        {
            if (_eventQueue.Count == 0)
                return null;

            var nrfEvent = (Nrf8001Event)_eventQueue.Dequeue();

            // Device events
            if (nrfEvent.EventType == Nrf8001EventType.DeviceStarted)
            {
                State = (Nrf8001State)nrfEvent.Data[1];
                DataCreditAvailable = nrfEvent.Data[3];
            }

            return nrfEvent;
        }

        #region ACI Commands
        /// <summary>
        /// Enables or disables Test mode on the nRF8001.
        /// </summary>
        /// <remarks>Section 24.1</remarks>
        /// <param name="testFeature">The test feature to activate, or 0xFF to disable Test mode.</param>
        public void Test(byte testFeature)
        {
            AciSend(Nrf8001OpCode.Test, testFeature);
        }

        /// <summary>
        /// Requests an EchoEvent from the nRF8001 containing the specified data.
        /// </summary>
        /// <remarks>Section 24.2</remarks>
        /// <param name="data">The data to be contained in the EchoEvent.</param>
        public void Echo(params byte[] data)
        {
            if (State != Nrf8001State.Test)
                throw new InvalidOperationException("The device is not in Test mode.");

            AciSend(Nrf8001OpCode.Echo, data);
        }

        /// <summary>
        /// Uploads setup data generated by nRFgo Studio to the nRF8001.
        /// </summary>
        /// <remarks>Section 24.6</remarks>
        /// <param name="data">The setup data to upload.</param>
        public void Setup(byte[] data)
        {
            AciSend(Nrf8001OpCode.Setup, data);
        }

        /// <summary>
        /// Starts advertising and establishes a connection to a peer device.
        /// </summary>
        /// <remarks>Section 24.14</remarks>
        /// <param name="timeout">Advertisement time, in seconds.</param>
        /// <param name="advInterval">Advertisement interval, in periods of 0.625 milliseconds.</param>
        public void Connect(ushort timeout, ushort advInterval)
        {
            if (State != Nrf8001State.Standby)
                throw new InvalidOperationException("The device is not in Standby mode.");

            if (timeout < 0x0001 || timeout > 0x3FFF)
                throw new ArgumentOutOfRangeException("timeout", "Timeout must be between 0x0000 and 0x4000.");

            if (advInterval < 0x0020 || advInterval > 0x4000)
                throw new ArgumentOutOfRangeException("advInterval", "AdvInterval must be between 0x001F and 0x4001.");

            AciSend(Nrf8001OpCode.Connect, (byte)(timeout & 0xFF),
                                            (byte)(timeout >> 8 & 0xFF),
                                            (byte)(advInterval & 0xFF),
                                            (byte)(advInterval >> 8 & 0xFF));
        }
        #endregion

        #region ACI Interface
        protected void AciSend(Nrf8001OpCode opCode, params byte[] data)
        {
            if (data.Length > 30)
                throw new ArgumentOutOfRangeException("data", "Array is too long (max 30 bytes)");

            // Create ACI packet
            var packet = new byte[data.Length + 2];
            packet[0] = (byte)(data.Length + 1);
            packet[1] = (byte)opCode;
            Array.Copy(data, 0, packet, 2, data.Length);

            // Request transfer
            _rdy.DisableInterrupt();
            _req.Write(false);

            // Wait for RDY to go low
            while (_rdy.Read()) ;

            _spi.WriteLsb(packet);

            _req.Write(true);

            // Wait for RDY to go high
            while (!_rdy.Read()) ;
            _rdy.EnableInterrupt();
        }

        protected byte[] AciReceive()
        {
            var buffer = new byte[2];

            _req.Write(false);

            _spi.WriteReadLsb(new byte[2], buffer);

            if (buffer[1] > 0)
            {
                buffer = new byte[buffer[1]];
                _spi.WriteReadLsb(new byte[buffer.Length], buffer);
            }

            _req.Write(true);

            return buffer;
        }
        #endregion

        private void OnRdyInterrupt(uint data1, uint data2, DateTime time)
        {
            var nrfEvent = new Nrf8001Event(AciReceive());

            _eventQueue.Enqueue(nrfEvent);
        }
    }
}
